**数据归一化Normalization**

数据按最小值中心化处理后，再按极差缩放

可以用sklearn的**preprocessing.MinMaxScaler**实现，参数feature_range，希望把数据压缩到的范围

In [1]:
from sklearn.preprocessing import MinMaxScaler

data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]


In [2]:
# 理解data的结构，换成表看看是什么样子
import pandas as pd
pd.DataFrame(data)


0   1
0 -1.0   2
1 -0.5   6
2  0.0  10
3  1.0  18

In [9]:
# 分步实现归一化
scaler = MinMaxScaler() # 实例化, 这里可以加上scaler = MinMaxScaler(feature_range=[5,10])
scaler = scaler.fit(data) # fit本质上是生成min和max
result = scaler.transform(data) #通过接口导出结果
result


array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

实例化可以加上scaler = MinMaxScaler(feature_range=[5,10])
当x中

In [5]:
# 一步实现归一化
result_ = scaler.fit_transform(data)
result_

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [1]:
# 用numpy实现归一化
import numpy as np

X = np.array([[-1, 2], [-0.5, 6], [0, 10], [1, 18]])
# 归一化
X_nor = (X - X.min(axis=0) / (X.max(axis=0) - X.min(axis=0)))
X_nor

array([[-0.5  ,  1.875],
       [ 0.   ,  5.875],
       [ 0.5  ,  9.875],
       [ 1.5  , 17.875]])